// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using asp_net_sql.Data;

#nullable disable

namespace asp_net_sql.Migrations
{
    [DbContext(typeof(TicTacToeDbContext))]
    partial class TicTacToeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("asp_net_sql.Models.RowRoster", b =>
                {
                    b.Property<int>("RId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RId");

                    b.ToTable("TableRoster");
                });

            modelBuilder.Entity("asp_net_sql.Models.RowRosterEnum", b =>
                {
                    b.Property<int>("RosterEnum")
                        .HasColumnType("int");

                    b.Property<int>("UniColumn")
                        .HasColumnType("int");

                    b.HasKey("RosterEnum");

                    b.HasIndex("UniColumn")
                        .IsUnique();

                    b.ToTable("TableRosterEnum");
                });

            modelBuilder.Entity("asp_net_sql.Models.RowRoster", b =>
                {
                    b.HasOne("asp_net_sql.Models.RowRosterEnum", "RowRosterEnum")
                        .WithMany()
                        .HasForeignKey("RId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RowRosterEnum");
                });
#pragma warning restore 612, 618
        }
    }
}
