// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using asp_net_sql.Data;

#nullable disable

namespace asp_net_sql.Migrations
{
    [DbContext(typeof(TicTacToeDbContext))]
    partial class TicTacToeDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("asp_net_sql.Models.ChildTable", b =>
                {
                    b.Property<int>("ChildID")
                        .HasColumnType("int");

                    b.HasKey("ChildID")
                        .HasName("PK_CT_ChildID");

                    b.ToTable("ChildTable", (string)null);
                });

            modelBuilder.Entity("asp_net_sql.Models.ParentTable", b =>
                {
                    b.Property<int>("ParentID")
                        .HasColumnType("int");

                    b.Property<int>("UniColumn")
                        .HasColumnType("int");

                    b.HasKey("ParentID")
                        .HasName("PK_PT_ParentID");

                    b.HasIndex(new[] { "UniColumn" }, "UQ_PT_UniColumn")
                        .IsUnique();

                    b.ToTable("ParentTable", (string)null);
                });

            modelBuilder.Entity("asp_net_sql.Models.ChildTable", b =>
                {
                    b.HasOne("asp_net_sql.Models.ParentTable", "Child")
                        .WithOne("ChildTable")
                        .HasForeignKey("asp_net_sql.Models.ChildTable", "ChildID")
                        .HasPrincipalKey("asp_net_sql.Models.ParentTable", "UniColumn")
                        .IsRequired()
                        .HasConstraintName("FK_ChildID__PT_UniColumn");

                    b.Navigation("Child");
                });

            modelBuilder.Entity("asp_net_sql.Models.ParentTable", b =>
                {
                    b.Navigation("ChildTable");
                });
#pragma warning restore 612, 618
        }
    }
}
